apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoappserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappserver
  template:
    metadata:
      labels:
        app: todoappserver
    spec:
      volumes:
        - name: todoapp-vol
          persistentVolumeClaim:
            claimName: project-claim  
      containers:
        - name: todoappserver
          image: opeyemiorugun/todoapp:v4
          imagePullPolicy: Always
          volumeMounts:
            - name: todoapp-vol
              mountPath: /usr/src/project_app/app/static
          env:
            - name: TODO_API_URL
              value: "http://localhost:8081/todos" 
