apiVersion: v1
kind: Service
metadata:
    name: todoapp-svc
spec:
    type: ClusterIP
    selector: 
        app: todoappserver #from the selector in deployment.yaml 
    ports:
        - port: 2341
          protocol: TCP
          targetPort: 5000