apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pg-svc
  labels:
    app: postgres   # Labels on the Service itself (for humans/tools)
spec:
  ports:
    - port: 5432    # Port exposed by the Service
      name: db
  clusterIP: None   # Headless Service (required for StatefulSet)
  selector:
    app: pgdb       # Routes traffic to Pods with this label

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: exercises
  name: pg-stset
spec:
  serviceName: pg-svc  # Service that provides stable DNS for Pods
  replicas: 1

  selector:
    matchLabels:
      app: pgdb        # StatefulSet owns Pods with this label

  template:
    metadata:
      labels:
        app: pgdb      # Applied to Pods â†’ must match selector
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - name: db
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-details
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata-vol
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: pgdata-vol  # One PVC per Pod
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
