apiVersion: v1
kind: Service
metadata:
    namespace: project
    name: todo-backend-svc
spec:
    type: ClusterIP
    selector: 
        app: todobackend #from the selector in deployment.yaml 
    ports:
        - port: 2441
          protocol: TCP
          targetPort: 5000