apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: exercises
  name: app-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/log`)
      kind: Rule
      services:
        - name: randomstrgenerator-svc
          port: 2343
      middlewares:
        - name: strip-log-prefix

    - match: PathPrefix(`/pingpong`)
      kind: Rule
      services:
        - name: pingpong-svc
          port: 2342
      middlewares:
        - name: strip-log-prefix