apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstrgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomstrgenerator
  template:
    metadata:
      labels:
        app: randomstrgenerator
    spec:
      containers:
        - name: randomstrgenerator
          image: opeyemiorugun/rand_str_generator:v1
          imagePullPolicy: IfNotPresent