apiVersion: v1
kind: Service
metadata:
    name: randomstrgenerator-svc
spec:
    type: ClusterIP
    selector: 
        app: randomstrgenerator #from the selector in deployment.yaml 
    ports:
        - port: 2343
          protocol: TCP
          targetPort: 5000