apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappserver
  template:
    metadata:
      labels:
        app: todoappserver
    spec:
      containers:
        - name: todoappserver
          image: todoapp:v1
          imagePullPolicy: Never