apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappserver
  template:
    metadata:
      labels:
        app: todoappserver
    spec:
      volumes:
        - name: todoapp-vol
          persistentVolumeClaim:
            claimName: project-claim  
      containers:
        - name: todoappserver
          image: opeyemiorugun/todoapp:v3.2.4
          imagePullPolicy: Always
          volumeMounts:
            - name: todoapp-vol
              mountPath: /usr/src/project_app/app/static
