apiVersion: v1
kind: Service
metadata:
    name: todoapp-svc
spec:
    type: NodePort
    selector: 
        app: todoappserver #from the selector in deployment.yaml 
    ports:
        - name: http
          nodePort: 30043
          protocol: TCP
          port: 2341
          targetPort: 5000